### ISSUE TITLE
资产查询过期红包数据显示错误

### ISSUE THREAD

**Issue by baifan97** [asupc/qqbot#6]
实际上有即将过期的红包，但是显示为0

**Comment by asupc** [comment]
原因：
因为docker 构建时默认使用utc 时间，导致相差8个小时，所以脚本计算过期红包时错误。
解决方法（3选1即可）
1. 自己修改容器的时区后重启容器。
2. tg 群中有修复版。自己下载后替换原来的查询脚本，
3. 更新镜像，新版镜像已经默认将时区改成东8区。

**Comment by baifan97** [comment]
好的，谢谢大佬
